### ISSUE TITLE
the bot is apparently reading all or a large part of the message history before each reply.

### ISSUE THREAD

**Issue by S1gil0** [chrisrude/oobabot#14]
I'm running a cpu only version of alpaca 7b , I get 4 tokens per second more or less. when I use the bot in a chanel with some history, I get like 0.2 tokens per seccond. If i move to a channel without any history, the tokens per seccond come back to normal, 4 or so per sec.
Is there a way of connfig how much of the history of a channel it uses for context? I tried disabling read history in discord permissions but the bot cant reply to my messages.

**Comment by chrisrude** [comment]
The bot will read up to the past 20 messages in 0.1.4, which I just upped from 10 in 0.1.3.  I'm presently working on making all such options available via command line / config file, so that you can have more control over it.

FWIW I've found that having more context helps the bot produce better responses, hence changing the default.  But obviously having speedy responses is important too!  So best for it to be an option to support different scenarios.

For now, staying on 0.1.3 might be your best option, but I hope to get 0.1.5 out in the next few days.

**Comment by S1gil0** [comment]
ty so much, I love your project and im activelly trying to use it live. I'm trying to make a functional support or entertainment chatbot based on vicuña7b that can run on cpus. I will be waiting for the update!

**Comment by chrisrude** [comment]
Thanks so much, I really appreciate the love for the project.  It means a lot.

[v0.1.5](https://github.com/chrisrude/oobabot/releases/tag/v0.1.5) is out!
There is now a `--history-lines` command line argument, which will let you dial up or down the number of previous chat messages to send to the bot.

Closing now, but let me know if it doesn't work!
