### ISSUE TITLE
Stopping Strings

### ISSUE THREAD

**Issue by sidonsoft** [chrisrude/oobabot#26]
stop_markers:
    - '### End of Transcript ###<|endoftext|>'
    - <|endoftext|>
    - </s>

    stopping_strings: [</s>]

OUTPUT containts the stopping marker/string

`Neuromorphic chips are a type of artificial intelligence chip designed to mimic the functioning of biological neural networks found in the human brain. They are typically used for tasks such as image recognition, natural language processing, and decision-making. To simulate these chips on a GPU (Graphics Processing Unit), you can use deep learning frameworks like TensorFlow or PyTorch. These frameworks provide tools for building and training neural networks, which can then be deployed onto the GPU for faster computation.</s>`

**Comment by chrisrude** [comment]
Thanks for the info!  Currently the stopping_string will only work when it's on a line by itself.  In this example it looks like it's at the end of a line.

I'll work on making it work more generally.

**Comment by chrisrude** [comment]
This should be fixed in https://github.com/chrisrude/oobabot/commit/f5021703b9f892b2dece98c3572b675a2791bf54

When we get a stop token in the middle of a line, return all text up until the token, then stop responding.

Also, we now automatically add anything in "stopping_strings" to the list of stop tokens we're looking for.

@sidonsoft if you feel like / want to test this from main, go ahead, if not it should show up in the 0.1.8 release.
