### ISSUE TITLE
Config file not read

### ISSUE THREAD

**Issue by Urammar** [chrisrude/oobabot#49]
Despite it being called in a flag

`C:\MyShit\AI\Flan-t5-XXL\OobaBot>python -m oobabot --config C:\MyShit\AI\Flan-t5-XXL\OobaBot\config.yml`

And dont_split_responses: true in the config.yml file being set

`←[33;40m2023-06-22 07:39:19,834←[0m←[37;40m DEBUG ←[0m←[36;40mResponse Grouping: split into messages by sentence←[0m`

The bot will still split messages despite the setting, and will only merge with the flag instruction --dont-split-responses

**Comment by chrisrude** [comment]
Interesting.  I take it other settings are not being read from the config file either?


I've added 95cc19484b97063311ff77fe43d097ef554da646 which changes the behavior when config.yml can't be found.  The new behavior is to print an error and exit immediately, printing out the full path to the file it was unable to load.  Though since you're passing the full path anyway, I don't suspect that's the issue.

I'm curious what happens if you try pasting the .yml file into a validator like https://yamlchecker.com/.

Otherwise the only other thing I could suspect would be an issue running on Windows.  What version of python are you using?

**Comment by Urammar** [comment]
`persona: blah blah This chat requires emoji's to be typed as text between colons, e.g. :happy_face:`

that colon on the end killed it. Wrapped the whole thing in some "quote marks" and suddenly its a valid file.

Recommendation: Exactly what you already did, error message on failure to load!

**Comment by chrisrude** [comment]
Yay, glad it worked!  Will treat this as done pending the release with the config file error message fix.
